### ISSUE TITLE
Add stats to the opening of the README

### ISSUE THREAD

**Issue by yarikoptic** [dandi/dandi-api-webshots#16]
README.md should start with a summary per each action, which would show per each "action":
- minimal timing
- mean `+-` standard deviation timing
- maximal timing
- no timing ("timeout" or any other string)

minimal/maximal should be accompanied with references to the name and hyperlink to the corresponding dandiset section.
"no timing" - the list (with hyperlinks) to all dandisets which have no timing

This would allow us to quickly judge timing without skimming through all dandisets

**Comment by jwodder** [comment]
@yarikoptic Is this the sort of thing you had in mind?

<img width="948" alt="Screen Shot 2021-05-05 at 09 40 17" src="https://user-images.githubusercontent.com/98207/117150240-f655b600-ad85-11eb-8f6c-364faa1b58ad.png">

**Comment by yarikoptic** [comment]
yeah, nice! 
- errors seems to be off though -- there should be no errors besides for edit-metadata AFAIK
- do `.2f` formatting also for StdDev

**Comment by jwodder** [comment]
@yarikoptic The errors happened because, after a certain point, everything failed with "Invalid session id".

**Comment by yarikoptic** [comment]
> @yarikoptic The errors happened because, after a certain point, everything failed with "Invalid session id".

just to make sure: and that is the state you work with, and they will not be there on a fresh rerun, right?

**Comment by jwodder** [comment]
@yarikoptic 

> that is the state you work with

I don't understand the question.

> they will not be there on a fresh rerun, right?

The README will be completely regenerated on a fresh rerun, but it's entirely possible there will be errors again.
