### ISSUE TITLE
RF to run in subprocess'es

### ISSUE THREAD

**Issue by yarikoptic** [dandi/dandi-api-webshots#19]
would allow for 
- parallelization
- continue with a new driver in case of driver crash etc. See e.g. https://github.com/dandi/dandiarchive/issues/662  Trying to resurrect in the single process did not work, and I think it should work if entire subprocess quits and we just continue in a new one with the next webshot

so we pretty much need to 
- flatten the sequence of webshots to produce across all dandisets
- split the full list of jobs between N subprocesses brought into the pool, where each subprocess
  - would login
  - go through its sequence while providing records it has done, and upon "total error" a record with a list of records left TODO
  - master process would start a new subprocess feeding the list of records left TODO if any, to replace previous one in the pool

**Comment by jwodder** [comment]
@yarikoptic If an error occurs for a given page, how many further times should the page be retried?

**Comment by yarikoptic** [comment]
I was not even thinking about retrying for such severe cases since I am afraid it would just hide away the underlying problem (e.g. if crashes some times) and one of the purposes for this repo is to alert on timing **and** errors.

**Comment by jwodder** [comment]
@yarikoptic Your original description indicates that pages with "total error" should be retried.  Exactly how do you want errors handled?

**Comment by yarikoptic** [comment]
ah, probably was not clear in what I meant. By "total error" I meant just a condition/fact that page "crashed", not to count some "total number" of errors from X attempts.

**Comment by jwodder** [comment]
@yarikoptic While trying to test out the script, the login functions started hanging, and dumping a snapshot revealed:

![ratelimit](https://user-images.githubusercontent.com/98207/129215665-738368ad-a032-40f8-8638-c7805ad60988.png)

**Comment by yarikoptic** [comment]
is that while running locally?  just comment out `options.add_argument('--headless')` and can click there.  If it keeps coming, an alternative -- to handle it programmatically as was done for that simpler, but analogous "Authorize" at https://github.com/dandi/dandi-api-webshots-tools/blob/master/make_webshots.py#L119 

How many parallel processes you tried? may be we should not do more than 2 or even just 1 (so no parallel) just to get benefit from being able to recover and continue

**Comment by jwodder** [comment]
@yarikoptic It keeps happening if I comment out the headless setting, except that sometimes the script manages to click the "Authorize" button automatically and sometimes it doesn't; moreover, some processes end up encountering a "Social Network Login Failure".

I'm using the default workers setting, which for my computer is eight.  If I set `max_workers=2`, I don't get the "Authorize" screen, but all of the processes seem end up encountering a "Social Network Login Failure."

**Comment by yarikoptic** [comment]
ok. and with `max_workers=1`? (thus only use subprocess to be able to handle crashes and continue)

**Comment by jwodder** [comment]
@yarikoptic That seems to work fine.

**Comment by yarikoptic** [comment]
PR?

**Comment by jwodder** [comment]
@yarikoptic PR: https://github.com/dandi/dandi-api-webshots-tools/pull/1
