### ISSUE TITLE
github workflow: shouldn't it need chromium?

### ISSUE THREAD

**Issue by yarikoptic** [dandi/dandi-api-webshots#5]
Just now spotted that github actions has no chrome/chromium installed so it could be "driven" or is it present in the environment by default?

**Comment by jwodder** [comment]
[It's in the environment by default.](https://github.com/actions/virtual-environments/blob/main/images/linux/Ubuntu1804-README.md#browsers-and-drivers)

**Comment by yarikoptic** [comment]
oh, nice.  and you don't need to wrap the call to the script with `xvfb-run`?  I guess we could just wait for the first run to happen to see what would happen ;) it seems that View Data webshots are outdated ATM as I have pushed them manually awhile back and we did get some data uploaded since then

**Comment by jwodder** [comment]
> and you don't need to wrap the call to the script with `xvfb-run`?

I didn't need to do that on my machine, so it didn't occur to me that that might be a thing.

**Comment by yarikoptic** [comment]
locally if ran outside of xvfb-run it indeed works but pops up the browser window - use of xvfb-run avoids that since it provides an alternative X server.  but I guess we will see - since they have selenium installed, I guess may be the entire session is ok to run "headless"
